#server:
#  port: 8071

app:
  url:
spring:
  datasource:
    initialization-mode: always
    username: admin
    password: admin1234
    url: jdbc:mysql://database-1.coz3uh2yaw2j.us-east-2.rds.amazonaws.com/banking_db

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect